[package]
name = "gmk-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inflate = "0.4.5"
nom = "7.1.3"
nom-derive = "0.10.0"
